patchtest-oe-post: remove pattern, include series parameter
pattern parameter was causing issues, so for the moment remove it.
Include the series parameter so we can test specific series.revisions

Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalez@linux.intel.com>

diff --git a/scripts/patchtest-oe-post b/scripts/patchtest-oe-post
--- a/scripts/patchtest-oe-post
+++ b/scripts/patchtest-oe-post
@@ -20,19 +20,28 @@
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
 function usage() {
-    echo -e "\$ $0 -r <repodir> -s <startdir> -R <resultsdir> -p <pattern>"
+    cat << EOF
+\$ $(basename $0) -r <repodir> -s <startdir> -R <resultsdir> -e <series>
+
+where
+
+    <repodir>   : Repository which is tracked by Patchwork. Default: '$repodir'
+    <startdir>  : Start directory for test discovery (patchtest --help, for more info). Default: '$startdir'
+    <resultsdir>: Output directory containing results. Default: '$resultsdir'
+    <series>    : One or more <seriesid>.<revisionid> separated by spaces. Default: '$series'
+                  If not specified, the git-pw timestamp file will be used
+EOF
+>&2
+
     exit 1
 }
 
-#Check the number of arguments
-NUMARGS=$#
-if [ ! $NUMARGS -ge 6 ]; then
-    usage
-fi
+repodir=''
+startdir=''
+resultsdir='/tmp/patchtest'
+newseries=''
 
-pattern='*'
-
-while getopts ":r:s:R:p:h" opt; do
+while getopts ":r:s:R:e:h" opt; do
     case $opt in
 	r)
 	    repodir=$OPTARG
@@ -43,8 +52,8 @@ while getopts ":r:s:R:p:h" opt; do
 	R)
 	    resultsdir=$OPTARG
 	    ;;
-	p)
-	    pattern=$OPTARG
+	e)
+	    newseries=$OPTARG
 	    ;;
 	h)
 	    usage
@@ -60,9 +69,16 @@ while getopts ":r:s:R:p:h" opt; do
     esac
 done
 
+# must parameters
+[ -z $repodir ] && { echo -e 'Repository missing'; usage; }
+[ -z $repodir ] && { echo -e 'Repository missing'; usage; }
+[ -z $repodir ] && { echo -e 'Repository missing'; usage; }
+
 [ ! -d ${resultsdir} ] && { mkdir -p ${resultsdir}; }
 
-newseries="$(patchtest-oe-poll-series ${repodir})"
+if [ -z $newseries ]; then
+    newseries="$(patchtest-oe-poll-series ${repodir})"
+fi
 
 failure="failure"
 success="success"
@@ -81,17 +97,22 @@ for seriesrev in ${newseries}; do
 	patchtest - \
 	    -C $repodir \
 	    -s $startdir \
-	    -p $pattern \
 	    -j \
     ) >  $rawsummary
 
+    # dont post if something went wrong
+    if [ "$?" -ne "0" ]; then
+       echo -e "patchtest return a non-zero code, skipping posting for series $series revision $revision" >&2
+       continue
+    fi
+
     # create the final summary
     if [ "$(cat ${rawsummary} | patchtest-oe-any-fail)" == "yes" ]; then
-	cat ${rawsummary} | grep '"status": "FAIL"' | patchtest-oe-summary > ${finalsummary}
+	cat ${rawsummary} | grep '"status": "FAIL"' | patchtest-oe-summary $series $revision > ${finalsummary}
 	result=$failure
     else
 	# produce the summary to be post to patchwork
-	cat ${rawsummary} | patchtest-oe-summary > ${finalsummary}
+	cat ${rawsummary} | patchtest-oe-summary $series $revision > ${finalsummary}
 	result=$success
     fi
 
@@ -104,5 +125,5 @@ for seriesrev in ${newseries}; do
 	--summary-from-file ${finalsummary} \
     )
 
-    echo "Tested Series: ${series}. Result: ${result}."
+    echo -e "Tested Series: ${series}. Result: ${result}." >&2
 done
